# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s3:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.1.1/24]
      nameservers:
        addresses: [192.168.1.1]
        search: [frsasir.net]
      gateway4: 192.168.1.1
    enp0s8:
      dhcp4: no
      dhcp6: no
      addresses: [10.0.1.10/24]
      #nameservers:
       # addresses: [10.0.1.1]
      gateway4: 10.0.1.1
